/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JudgeRouteImport } from './routes/judge'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamScoresRouteImport } from './routes/team.scores'
import { Route as TeamLeaderboardRouteImport } from './routes/team.leaderboard'
import { Route as JudgeScoreRouteImport } from './routes/judge.score'
import { Route as JudgeLeaderboardRouteImport } from './routes/judge.leaderboard'
import { Route as AdminLeaderboardRouteImport } from './routes/admin.leaderboard'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminCriteriaRouteImport } from './routes/admin.criteria'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeRoute = JudgeRouteImport.update({
  id: '/judge',
  path: '/judge',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamScoresRoute = TeamScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => TeamRoute,
} as any)
const TeamLeaderboardRoute = TeamLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => TeamRoute,
} as any)
const JudgeScoreRoute = JudgeScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => JudgeRoute,
} as any)
const JudgeLeaderboardRoute = JudgeLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => JudgeRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCriteriaRoute = AdminCriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/judge': typeof JudgeRouteWithChildren
  '/login': typeof LoginRoute
  '/team': typeof TeamRouteWithChildren
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/judge/leaderboard': typeof JudgeLeaderboardRoute
  '/judge/score': typeof JudgeScoreRoute
  '/team/leaderboard': typeof TeamLeaderboardRoute
  '/team/scores': typeof TeamScoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/judge': typeof JudgeRouteWithChildren
  '/login': typeof LoginRoute
  '/team': typeof TeamRouteWithChildren
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/judge/leaderboard': typeof JudgeLeaderboardRoute
  '/judge/score': typeof JudgeScoreRoute
  '/team/leaderboard': typeof TeamLeaderboardRoute
  '/team/scores': typeof TeamScoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/judge': typeof JudgeRouteWithChildren
  '/login': typeof LoginRoute
  '/team': typeof TeamRouteWithChildren
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/judge/leaderboard': typeof JudgeLeaderboardRoute
  '/judge/score': typeof JudgeScoreRoute
  '/team/leaderboard': typeof TeamLeaderboardRoute
  '/team/scores': typeof TeamScoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/judge'
    | '/login'
    | '/team'
    | '/admin/criteria'
    | '/admin/events'
    | '/admin/leaderboard'
    | '/judge/leaderboard'
    | '/judge/score'
    | '/team/leaderboard'
    | '/team/scores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/judge'
    | '/login'
    | '/team'
    | '/admin/criteria'
    | '/admin/events'
    | '/admin/leaderboard'
    | '/judge/leaderboard'
    | '/judge/score'
    | '/team/leaderboard'
    | '/team/scores'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/judge'
    | '/login'
    | '/team'
    | '/admin/criteria'
    | '/admin/events'
    | '/admin/leaderboard'
    | '/judge/leaderboard'
    | '/judge/score'
    | '/team/leaderboard'
    | '/team/scores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  JudgeRoute: typeof JudgeRouteWithChildren
  LoginRoute: typeof LoginRoute
  TeamRoute: typeof TeamRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge': {
      id: '/judge'
      path: '/judge'
      fullPath: '/judge'
      preLoaderRoute: typeof JudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/scores': {
      id: '/team/scores'
      path: '/scores'
      fullPath: '/team/scores'
      preLoaderRoute: typeof TeamScoresRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/leaderboard': {
      id: '/team/leaderboard'
      path: '/leaderboard'
      fullPath: '/team/leaderboard'
      preLoaderRoute: typeof TeamLeaderboardRouteImport
      parentRoute: typeof TeamRoute
    }
    '/judge/score': {
      id: '/judge/score'
      path: '/score'
      fullPath: '/judge/score'
      preLoaderRoute: typeof JudgeScoreRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/judge/leaderboard': {
      id: '/judge/leaderboard'
      path: '/leaderboard'
      fullPath: '/judge/leaderboard'
      preLoaderRoute: typeof JudgeLeaderboardRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/criteria': {
      id: '/admin/criteria'
      path: '/criteria'
      fullPath: '/admin/criteria'
      preLoaderRoute: typeof AdminCriteriaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCriteriaRoute: typeof AdminCriteriaRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCriteriaRoute: AdminCriteriaRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface JudgeRouteChildren {
  JudgeLeaderboardRoute: typeof JudgeLeaderboardRoute
  JudgeScoreRoute: typeof JudgeScoreRoute
}

const JudgeRouteChildren: JudgeRouteChildren = {
  JudgeLeaderboardRoute: JudgeLeaderboardRoute,
  JudgeScoreRoute: JudgeScoreRoute,
}

const JudgeRouteWithChildren = JudgeRoute._addFileChildren(JudgeRouteChildren)

interface TeamRouteChildren {
  TeamLeaderboardRoute: typeof TeamLeaderboardRoute
  TeamScoresRoute: typeof TeamScoresRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamLeaderboardRoute: TeamLeaderboardRoute,
  TeamScoresRoute: TeamScoresRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  JudgeRoute: JudgeRouteWithChildren,
  LoginRoute: LoginRoute,
  TeamRoute: TeamRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
